spring:
  profiles:
    active: dev
  application:
    name: service1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_db
    username: root
    password: Hatsunemiku39$
  jpa:
    hibernate:
      ddl-auto: create # Try create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        transaction:
          coordinator_class: org.hibernate.transaction.JDBCTransactionFactory
    defer-datasource-initialization: true
  show-sql: true
  h2:
    console:
      enabled: true
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
logging:
  level:
    org.hibernate.SQL: DEBUG  # Logs SQL queries
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Logs parameter binding
    org.hibernate.tool.hbm2ddl: TRACE  # Log the DDL schema creation (e.g., CREATE TABLE)
